### PR TITLE
feat: Add optional argument to specify custom path to download LLM

### LINKED ISSUE #5: feat: Add optional argument to specify custom path to download LLM
Currently there is no implementation to specify custom path location to download a model.

By default, the model is downloaded at `~/onprem_data`

Example:

```py
from onprem import LLM

llm = LLM(model_download_path="~/models")
# or
llm.download_model(model_download_path="~/models")
```

### PR DESCRIPTION
**Pull request by rabilrbl**
Resolves #5 

This PR will enable to pass an optional argument `model_download_path` for `LLM` and `LLM.download_model` to set custom path location for model download.

### CODE REVIEW

**Comment by amaiya** [comment]
In your PR, the `check_model` method is still always loading the model from `~/onprem_data`.  The model is never loaded from the supplied download location.

**Comment by rabilrbl** [comment]
> In your PR, the `check_model` method is still always loading the model from `~/onprem_data`. So, the model is never loaded from the supplied custom download location.

@amaiya I can create an instance variable `self.model_download_path` and trigger at `check_model` method.
I feel it's better to disable `model_download_path` argument for `.download_model()` method, as passing an updated location will not effect in `check_model()` method. So that `self.model_download_path` will always be in sync as instance variable. What say? 

Do you have a better implementaion?

**Comment by rabilrbl** [comment]
@amaiya Fixed ✅

**Comment by amaiya** [comment]
Great - thanks a lot, @rabilrbl. Instead of putting `model_download_path or U.get_datadir()` in multiple places, it would probably be better to insert it once in the constructor to remove the risk of future contributors forgetting to check both when they want to access the download path. I can make that adjustment after merging.  Thanks again!

**Pull request merged**
